const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const root=path.resolve(__dirname,'..');
let backend;const getBackend=async()=>backend||(backend=await import('../cloudflare/worker.mjs'));
class SQL {
  constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(fs.readFileSync(path.join(root,'cloudflare/schema.sql'),'utf8'));}
  withSession(mode){assert.equal(mode,'first-primary');return this;}
  prepare(sql){const database=this;return {values:[],bind(...values){this.values=values;return this;},async first(){return database.sqlite.prepare(sql).get(...this.values)||null;},async all(){return {results:database.sqlite.prepare(sql).all(...this.values)};},async run(){const r=database.sqlite.prepare(sql).run(...this.values);return {meta:{changes:Number(r.changes)}};},sync(){const r=database.sqlite.prepare(sql).run(...this.values);return {meta:{changes:Number(r.changes)}};}};}
  async batch(statements){if(this.beforeBatch){const fn=this.beforeBatch;this.beforeBatch=null;fn();}this.sqlite.exec('BEGIN');try{const results=statements.map(s=>s.sync());this.sqlite.exec('COMMIT');return results;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}
}
function fixture(){return {props:[{id:'p',name:'Villa Mar',notes:'PRIVATE PROPERTY NOTES',photos:['PRIVATE PHOTO']},{id:'q',name:'La Forca'}],cleaners:[{id:'a',name:'Maribel',phone:'PRIVATE PHONE'},{id:'b',name:'Emi'},{id:'team',name:'Alina'}],sessions:[{id:'s',propId:'p',date:'2000-06-01',time:'10:00',status:'scheduled',note:'PRIVATE CLEANING NOTE',crew:{main:[{cleanerId:'a',name:'Maribel',status:'offered'},{cleanerId:'b',name:'Emi',status:'confirmed'}],alinaSpots:0,alinaStatus:'offered'},cleanerIds:['a','b']},{id:'t',propId:'q',date:'2000-06-02',time:'10:00',status:'scheduled',cleanerIds:[],crew:{main:[],alinaSpots:3,alinaStatus:'offered'}}],bookings:[{id:'booking',propId:'p',checkIn:'2000-05-25',checkOut:'2000-06-01',guestName:'PRIVATE GUEST',totalPrice:987654,notes:'PRIVATE BOOKING NOTE',guestCount:8},{id:'next',propId:'p',checkIn:'2000-06-01',checkOut:'2000-06-08',guestName:'PRIVATE NEXT GUEST',totalPrice:567890},{id:'cancelled',propId:'q',checkIn:'2000-06-01',checkOut:'2000-06-02',status:'cancelled',guestName:'PRIVATE CANCELED',retainedRevenue:321}],tasks:[{id:'task',note:'PRIVATE TASK'}],contacts:[{name:'PRIVATE CONTACT'}],scratch:'PRIVATE SCRATCH',_savedAt:1,_migrations:['bk_excel_2026_v1','bk_excel_2027_v1']};}
async function setup(active=true){const worker=await getBackend(),sql=new SQL(),original=JSON.stringify(fixture());const env={SECRET:'SYNTHETIC_MANAGER_KEY',STAFF_DB:sql,DB:{value:original,async get(){return this.value;},async put(key,value){assert.equal(key,'seravillas');this.value=value;}}};
  async function call(route='/',method='GET',payload,headers={}){return worker.default.fetch(new Request('https://service.invalid'+route,{method,headers:{'Content-Type':'application/json',...headers},...(payload===undefined?{}:{body:JSON.stringify(payload)})}),env);}
  const manager=(route='/',method='GET',payload,headers={})=>call(route,method,payload,{'X-Secret':env.SECRET,...headers});
  if(active){const res=await manager('/api/admin/migrate','POST',{sourceHash:await worker.digest(original)});assert.equal(res.status,200);}
  const account=async id=>{const res=await manager('/api/admin/accounts','POST',{cleanerId:id,action:'issue'});assert.equal(res.status,200);return (await res.json()).accessCode;};
  const schedule=async code=>{const res=await call('/api/cleaner/schedule?start=2000-05-29&end=2000-06-04','GET',undefined,{Authorization:'Bearer '+code});assert.equal(res.status,200);return res.json();};
  return {worker,sql,env,call,manager,account,schedule,original};
}
const op=(session,action,kind='main')=>({operationId:crypto.randomUUID(),sessionId:session.id,kind,version:session.own.find(o=>o.kind===kind).version,action});
test('activation requires manager and exact backed-up KV hash; existing KV stays unchanged',async()=>{const app=await setup(false);assert.equal((await app.call('/api/admin/migrate','POST',{})).status,401);assert.equal((await app.manager('/api/admin/migrate','POST',{sourceHash:'wrong'})).status,409);assert.equal((await app.manager('/api/admin/capabilities')).status,200);const initial=await app.manager('/');assert.equal(initial.headers.get('ETag'),null);assert.equal(await initial.text(),app.original);assert.equal((await app.manager('/api/admin/migrate','POST',{sourceHash:await app.worker.digest(app.original)})).status,200);assert.equal(app.env.DB.value,app.original);assert.equal((await app.manager('/api/admin/migrate','POST',{sourceHash:await app.worker.digest(app.original)})).status,409);assert.deepEqual(await (await app.manager('/')).json(),fixture());});
test('manager saves require a current version; old clients and simultaneous stale saves cannot overwrite',async()=>{const app=await setup();const initial=await app.manager('/'),tag=initial.headers.get('ETag'),data=await initial.json();assert.equal((await app.manager('/','POST',data)).status,428);const first=await app.manager('/','POST',{...data,scratch:'NEW MANAGER NOTE'},{'If-Match':tag});assert.equal(first.status,200);assert.equal((await app.manager('/','POST',{...data,scratch:'STALE NOTE'},{'If-Match':tag})).status,409);assert.equal((await (await app.manager('/')).json()).scratch,'NEW MANAGER NOTE');assert.equal((await app.manager('/','POST',{bad:true},{'If-Match':first.headers.get('ETag')})).status,400);});
test('cleaner codes are random and stored only as hashes; restricted responses exclude all private fields',async()=>{const app=await setup(),code=await app.account('a');assert.match(code,/^[a-f0-9]{64}$/);const row=app.sql.sqlite.prepare('SELECT * FROM cleaner_accounts').get();assert.notEqual(row.token_hash,code);assert.equal(row.token_hash,await app.worker.digest(code));const schedule=await app.schedule(code),text=JSON.stringify(schedule);assert.ok(!text.includes('PRIVATE'));assert.ok(!text.includes('987654'));assert.equal(schedule.user.id,'a');assert.equal(schedule.sessions.length,2);assert.equal(schedule.sessions[0].crew.main.length,2);assert.equal(schedule.sessions[0].own.length,1);assert.equal(schedule.sessions[1].own.length,0);assert.equal(schedule.stays.length,2);assert.equal((await app.call('/','GET',undefined,{Authorization:'Bearer '+code})).status,401);assert.equal((await app.call('/api/admin/accounts','GET',undefined,{Authorization:'Bearer '+code})).status,401);assert.equal((await app.call('/api/admin/accounts','POST',{cleanerId:'b',action:'issue'},{Authorization:'Bearer '+code})).status,401);});
test('no configured manager secret fails closed and foreign origins are rejected',async()=>{const app=await setup();delete app.env.SECRET;assert.equal((await app.call('/')).status,401);assert.equal((await app.call('/','GET',undefined,{Origin:'https://untrusted.invalid','X-Secret':'SYNTHETIC_MANAGER_KEY'})).status,403);const response=await app.call('/','OPTIONS',undefined,{Origin:'https://antonioseravillas.github.io'});assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://antonioseravillas.github.io');assert.equal(response.headers.get('Access-Control-Expose-Headers'),'ETag');});
test('cleaners can confirm and complete only their own work; bookings and other staff remain intact',async()=>{const app=await setup(),code=await app.account('a');let schedule=await app.schedule(code);const headers={Authorization:'Bearer '+code};let res=await app.call('/api/cleaner/assignment','POST',op(schedule.sessions[0],'confirm'),headers);assert.equal(res.status,200);schedule=await app.schedule(code);res=await app.call('/api/cleaner/assignment','POST',op(schedule.sessions[0],'complete'),headers);assert.equal(res.status,200);const result=await (await app.manager('/')).json();assert.deepEqual(result.bookings,fixture().bookings);assert.deepEqual(result.tasks,fixture().tasks);assert.deepEqual(result.contacts,fixture().contacts);assert.equal(result.sessions[0].note,'PRIVATE CLEANING NOTE');assert.equal(result.sessions[0].status,'scheduled');assert.equal(result.sessions[0].crew.main[0].status,'confirmed');assert.ok(result.sessions[0].crew.main[0].completedAt);assert.deepEqual(result.sessions[0].crew.main[1],fixture().sessions[0].crew.main[1]);const forbidden={...op(schedule.sessions[0],'decline'),sessionId:'t'};assert.equal((await app.call('/api/cleaner/assignment','POST',forbidden,headers)).status,403);assert.equal((await app.call('/api/cleaner/assignment','POST',{...op(schedule.sessions[0],'confirm'),guestName:'hacked'},headers)).status,400);});
test('offline retries apply once and cannot reuse another user’s operation ID',async()=>{const app=await setup(),code=await app.account('a'),codeB=await app.account('b'),schedule=await app.schedule(code),input=op(schedule.sessions[0],'confirm'),headers={Authorization:'Bearer '+code};const first=await app.call('/api/cleaner/assignment','POST',input,headers),receipt=await first.json();assert.equal(first.status,200);const retry=await app.call('/api/cleaner/assignment','POST',input,headers);assert.deepEqual(await retry.json(),receipt);assert.equal((await app.manager('/')).headers.get('ETag'),'"sv-2"');assert.equal((await app.call('/api/cleaner/assignment','POST',input,{Authorization:'Bearer '+codeB})).status,409);assert.equal((await app.call('/api/cleaner/assignment','POST',{...input,action:'decline'},headers)).status,409);});
test('rescheduling invalidates offline approvals while unrelated changes can be safely combined',async()=>{const app=await setup(),code=await app.account('a'),schedule=await app.schedule(code),input=op(schedule.sessions[0],'confirm');let remote=await app.manager('/'),data=await remote.json();data.sessions[0].date='2000-06-03';assert.equal((await app.manager('/','POST',data,{'If-Match':remote.headers.get('ETag')})).status,200);assert.equal((await app.call('/api/cleaner/assignment','POST',input,{Authorization:'Bearer '+code})).status,409);const fresh=await app.schedule(code),newInput=op(fresh.sessions.find(s=>s.id==='s'),'confirm');app.sql.beforeBatch=()=>{const row=app.sql.sqlite.prepare('SELECT * FROM app_state').get(),latest=JSON.parse(row.json);latest.tasks.push({id:'concurrent',note:'Manager work'});app.sql.sqlite.prepare('UPDATE app_state SET json=?,revision=revision+1,last_op=?').run(JSON.stringify(latest),'manager-change');};assert.equal((await app.call('/api/cleaner/assignment','POST',newInput,{Authorization:'Bearer '+code})).status,200);data=await (await app.manager('/')).json();assert.equal(data.tasks.at(-1).id,'concurrent');assert.equal(data.sessions[0].crew.main[0].status,'confirmed');});
test('Alina can update aggregate team work; another cleaner cannot change those spots',async()=>{const app=await setup(),code=await app.account('team'),schedule=await app.schedule(code),input=op(schedule.sessions[1],'confirm','alina');assert.equal((await app.call('/api/cleaner/assignment','POST',input,{Authorization:'Bearer '+code})).status,200);const data=await (await app.manager('/')).json();assert.equal(data.sessions[1].crew.alinaStatus,'confirmed');assert.equal(data.sessions[1].crew.alinaSpots,3);const other=await app.account('a');assert.equal((await app.call('/api/cleaner/assignment','POST',{...input,operationId:crypto.randomUUID(),action:'decline'},{Authorization:'Bearer '+other})).status,403);});
test('disabled or replaced codes stop both schedule reads and writes',async()=>{const app=await setup(),code=await app.account('a'),schedule=await app.schedule(code);await app.manager('/api/admin/accounts','POST',{cleanerId:'a',action:'revoke'});assert.equal((await app.call('/api/cleaner/schedule?start=2000-05-29&end=2000-06-04','GET',undefined,{Authorization:'Bearer '+code})).status,401);assert.equal((await app.call('/api/cleaner/assignment','POST',op(schedule.sessions[0],'confirm'),{Authorization:'Bearer '+code})).status,401);const newCode=await app.account('a');assert.notEqual(newCode,code);assert.equal((await app.schedule(newCode)).user.id,'a');});
test('future work, completed sessions, malformed date ranges and excessive payloads are rejected',async()=>{const app=await setup(),code=await app.account('b'),schedule=await app.schedule(code),headers={Authorization:'Bearer '+code};const before=fixture();before.sessions[0].date='2999-01-01';assert.throws(()=>app.worker.applyAssignment(before,'b',{sessionId:'s',kind:'main',action:'complete'},'2026-10-01','now'),/Future work/);before.sessions[0].status='done';assert.throws(()=>app.worker.applyAssignment(before,'b',{sessionId:'s',kind:'main',action:'decline'},'2026-10-01','now'),/closed/);assert.equal((await app.call('/api/cleaner/schedule?start=2000-02-30&end=2000-03-04','GET',undefined,headers)).status,400);assert.equal((await app.call('/api/cleaner/assignment','POST',{...op(schedule.sessions[0],'complete'),extra:'x'.repeat(5000)},headers)).status,413);});
test('legacy named assignments can report completion without modifying their booking or another session',async()=>{const app=await setup();let response=await app.manager('/'),data=await response.json();delete data.sessions[0].crew;data.sessions[0].cleanerIds=['a','b'];await app.manager('/','POST',data,{'If-Match':response.headers.get('ETag')});const code=await app.account('a'),schedule=await app.schedule(code);assert.equal((await app.call('/api/cleaner/assignment','POST',op(schedule.sessions[0],'complete'),{Authorization:'Bearer '+code})).status,200);const after=await (await app.manager('/')).json();assert.deepEqual(after.sessions[1],fixture().sessions[1]);assert.equal(after.sessions[0].crew.main[0].status,'confirmed');assert.ok(after.sessions[0].crew.main[0].completedAt);});

test('compressed response versions accept the same revision and reject stale or wildcard versions',async()=>{const app=await setup(),initial=await app.manager('/'),tag=initial.headers.get('ETag'),data=await initial.json();assert.equal((await app.manager('/','POST',data,{'If-Match':'W/'+tag})).status,200);assert.equal((await app.manager('/','POST',data,{'If-Match':'W/'+tag})).status,409);assert.equal((await app.manager('/','POST',data,{'If-Match':'*'})).status,409);const fresh=await app.manager('/');assert.equal((await app.manager('/','POST',data,{'If-Match':'W/'+fresh.headers.get('ETag')})).status,200);});
